// SPDX-License-Identifier: Apache-2.0

package emit

import (
	"text/template"
)

// Templates contains all code generation templates.
var Templates *template.Template

func init() {
	Templates = template.Must(template.New("").Parse(allTemplates))
}

const allTemplates = `
{{- define "file" -}}
// Code generated by modelsdk-codegen. DO NOT EDIT.
// Source: {{.Version}}-structures.json

package {{.PackageName}}

{{if .Imports}}
import (
{{- range $imp, $_ := .Imports}}
	"{{$imp}}"
{{- end}}
)
{{end}}

{{range .Interfaces}}
{{template "interface" .}}

{{end}}
{{range .Types}}
{{template "struct" .}}

{{end}}
{{- end}}

{{- define "interface" -}}
{{.Comment}}
type {{.Name}} interface {
	{{.MarkerMethod}}()
}
{{- end}}

{{- define "struct" -}}
{{.Comment}}
type {{.Name}} struct {
	model.BaseElement
{{- range .Fields}}
	{{.Name}} {{.GoType}} ` + "`" + `json:"{{.JSONTag}}{{if .OmitEmpty}},omitempty{{end}}"` + "`" + `
{{- end}}
}
{{range .MarkerMethods}}
func (*{{$.Name}}) {{.}}() {}
{{end}}
{{- end}}

{{- define "enums" -}}
// Code generated by modelsdk-codegen. DO NOT EDIT.
// Source: {{.Version}}-structures.json

package {{.PackageName}}

{{range $enum := .Enums}}
{{$enum.Comment}}
type {{$enum.Name}} string

const (
{{- range $enum.Values}}
	{{.Name}} {{$enum.Name}} = "{{.Value}}"
{{- end}}
)

{{end}}
{{- end}}
`

// FileData contains data for rendering a types file.
type FileData struct {
	Version     string
	PackageName string
	Imports     map[string]bool
	Interfaces  []*InterfaceData
	Types       []*TypeData
}

// InterfaceData contains data for rendering an interface.
type InterfaceData struct {
	Name         string
	Comment      string
	MarkerMethod string
}

// TypeData contains data for rendering a struct.
type TypeData struct {
	Name          string
	Comment       string
	Fields        []*FieldData
	MarkerMethods []string
}

// FieldData contains data for rendering a struct field.
type FieldData struct {
	Name      string
	GoType    string
	JSONTag   string
	OmitEmpty bool
}

// EnumsFileData contains data for rendering an enums file.
type EnumsFileData struct {
	Version     string
	PackageName string
	Enums       []*EnumData
}

// EnumData contains data for rendering an enum type.
type EnumData struct {
	Name    string
	Comment string
	Values  []*EnumValueData
}

// EnumValueData contains data for rendering an enum constant.
type EnumValueData struct {
	Name  string
	Value string
}
