#set document(title: none)
#set page(paper: "a4", margin: (x: 2cm, y: 2.5cm))
#set text(size: 11pt)
#set heading(numbering: "1.1")
#show heading.where(level: 1): it => {
  v(1em)
  text(size: 16pt, weight: "bold", it)
  v(0.5em)
}
#show heading.where(level: 2): it => {
  v(0.8em)
  text(size: 13pt, weight: "bold", it)
  v(0.3em)
}
#show heading.where(level: 3): it => {
  v(0.5em)
  text(size: 11pt, weight: "bold", it)
  v(0.2em)
}
#show raw.where(block: true): it => {
  set text(size: 9pt)
  block(fill: luma(245), inset: 10pt, radius: 4pt, width: 100%, it)
}
#show raw.where(block: false): it => {
  box(fill: luma(240), inset: (x: 3pt, y: 0pt), radius: 2pt, it)
}

// Define pandoc compatibility functions
#let horizontalrule = line(length: 100%, stroke: 0.5pt + gray)

= mxcli: AI-Powered Development for Mendix
<mxcli-ai-powered-development-for-mendix>
== Slide Deck for Presentation
<slide-deck-for-presentation>

#horizontalrule

== Slide 1: Title
<slide-1-title>
= mxcli
<mxcli>
== AI-Powered Development for Mendix
<ai-powered-development-for-mendix>
#strong[Accelerate Mendix Development with Natural Language and Code Generation]

#horizontalrule

== Slide 2: The Challenge
<slide-2-the-challenge>
=== Traditional Mendix Development
<traditional-mendix-development>
- Visual modeling is powerful but #strong[click-intensive]
- AI tools struggle with #strong[binary/JSON model formats]
- Limited ability to #strong[batch modify] multiple elements
- Difficult to #strong[review changes] in pull requests
- #strong[Context limitations] when using GenAI APIs

#horizontalrule

== Slide 3: The Solution
<slide-3-the-solution>
=== Introducing mxcli
<introducing-mxcli>
A command-line interface that brings #strong[AI-powered development] to Mendix

- #strong[MDL] (Mendix Definition Language) - SQL-like syntax for models
- #strong[Read & write] Mendix projects programmatically
- #strong[Native integration] with AI coding assistants
- Works with #strong[local .mpr files] and #strong[Studio Pro]

#horizontalrule

== Slide 4: Key Benefits
<slide-4-key-benefits>
=== Why mxcli?
<why-mxcli>
#figure(
  align(center)[#table(
    columns: 2,
    align: (auto,auto,),
    table.header([Benefit], [Impact],),
    table.hline(),
    [#strong[10x Faster Development];], [Natural language to working features],
    [#strong[Token Efficient];], [5-10x fewer tokens than JSON],
    [#strong[Better Code Reviews];], [Human-readable diffs],
    [#strong[Consistent Standards];], [MDL templates enforce best practices],
    [#strong[Full Project Understanding];], [Agentic search capabilities],
  )]
  , kind: table
  )

#horizontalrule

== Slide 5: How It Works
<slide-5-how-it-works>
=== Architecture
<architecture>
```
┌─────────────────┐     ┌──────────────┐     ┌─────────────────┐
│   Developer     │     │    mxcli     │     │ Mendix Project  │
│   or AI Agent   │────▶│  (MDL REPL)  │────▶│   (.mpr file)   │
│                 │ MDL │              │     │                 │
│ "Create a       │     │ Parses MDL   │     │ Creates actual  │
│  Customer       │     │ Validates    │     │ entities,       │
│  entity..."     │     │ Executes     │     │ microflows,     │
└─────────────────┘     └──────────────┘     │ pages, etc.     │
                                             └─────────────────┘
```

#horizontalrule

== Slide 6: The MDL Advantage
<slide-6-the-mdl-advantage>
=== Compared to JSON Model Representations
<compared-to-json-model-representations>
- #strong[Generated by AI] - LLMs produce syntactically correct MDL
- #strong[Human-Readable Diffs] - Easier to review than binary/JSON
- #strong[High Information Density] - See complete microflow logic at a glance
- #strong[Token Efficient] - 5-10x fewer tokens than JSON
- #strong[Concise Skills] - Better AI instruction files = better output

#horizontalrule

== Slide 7: Token Efficiency
<slide-7-token-efficiency>
=== Why This Matters for GenAI
<why-this-matters-for-genai>
#figure(
  align(center)[#table(
    columns: 2,
    align: (auto,auto,),
    table.header([Representation], [Tokens (10-entity module)],),
    table.hline(),
    [JSON (raw model)], [\~15,000-25,000 tokens],
    [MDL], [\~2,000-4,000 tokens],
    [#strong[Savings];], [#strong[5-10x fewer tokens];],
  )]
  , kind: table
  )

#strong[Benefits:] - Lower API costs - More context in prompts - Larger scope operations - Better AI understanding

#horizontalrule

== Slide 8: Token Comparison
<slide-8-token-comparison>
=== JSON vs MDL
<json-vs-mdl>
#strong[JSON (\~180 tokens):]

```json
{
  "entity": {
    "name": "Customer",
    "attributes": [
      {"name": "Name", "type": {"type": "String", "length": 200}},
      {"name": "Email", "type": {"type": "String", "length": 200}}
    ]
  }
}
```

#strong[MDL (\~35 tokens):]

```sql
/** Customer master data */
CREATE PERSISTENT ENTITY Sales.Customer (
    Name: String(200),
    Email: String(200)
);
```

#horizontalrule

== Slide 9: MDL Example - Entities
<slide-9-mdl-example---entities>
=== Domain Model Definition
<domain-model-definition>
```sql
/** Order entity with audit support */
@Position(100, 100)
CREATE PERSISTENT ENTITY Sales.Order (
    OrderNumber: String(50) NOT NULL UNIQUE,
    OrderDate: DateTime DEFAULT '[%CurrentDateTime%]',
    TotalAmount: Decimal NOT NULL DEFAULT 0,
    Status: Enum Sales.OrderStatus DEFAULT 'Draft'
);

CREATE ASSOCIATION Sales.Order_Customer
    FROM Sales.Order TO Sales.Customer
    TYPE REFERENCE
    DELETE_BEHAVIOR DELETE_BUT_KEEP_REFERENCES;
```

#horizontalrule

== Slide 10: MDL Example - Microflows
<slide-10-mdl-example---microflows>
=== Business Logic
<business-logic>
```sql
/**
 * Process a new order submission.
 * Validates, updates inventory, sends confirmation.
 */
CREATE MICROFLOW Sales.SubmitOrder($order: Sales.Order)
RETURNS Boolean AS $success
BEGIN
    IF NOT CALL Sales.ValidateOrder($order) THEN
        RETURN false;
    END;

    CHANGE $order (Status = 'Submitted');
    COMMIT $order;
    CALL Sales.SendOrderConfirmation($order);
    RETURN true;
END;
```

#horizontalrule

== Slide 11: MDL Example - Pages
<slide-11-mdl-example---pages>
=== User Interface
<user-interface>
```sql
CREATE PAGE Sales.CustomerOverview
TITLE 'Customer Management'
LAYOUT 'Atlas_Core.Atlas_Default'
BEGIN
  LAYOUTGRID mainGrid
    ROW
      COLUMN (DESKTOP_WIDTH 12)
        DATAGRID CustomerGrid
          SOURCE DATABASE Sales.Customer
          SORT BY Name ASC
        BEGIN
          HEADER
            ACTIONBUTTON btnNew 'New' ACTION CREATE_OBJECT;
          COLUMN Name AS 'Customer Name';
          COLUMN Email AS 'Email';
        END;
END;
```

#horizontalrule

== Slide 12: AI Integration
<slide-12-ai-integration>
=== Claude Code Workflow
<claude-code-workflow>
```
your-mendix-project/
├── .claude/
│   └── skills/           # AI generation guides
│       ├── create-entity.md
│       ├── create-microflow.md
│       └── create-page.md
├── CLAUDE.md             # Project context
└── mxcli                 # CLI executable
```

#strong[Developer says:] "Create a customer management module"

#strong[AI generates:] Complete MDL with entities, microflows, and pages

#horizontalrule

== Slide 13: AI Generation Skills
<slide-13-ai-generation-skills>
=== Combining Capabilities
<combining-capabilities>
#figure(
  align(center)[#table(
    columns: 2,
    align: (auto,auto,),
    table.header([Skill], [Output],),
    table.hline(),
    [Domain Model], [Entities, associations, enumerations],
    [Overview Pages], [Data grids with CRUD buttons],
    [Detail Pages], [Edit forms with validation],
    [Validation Microflows], [Business rule enforcement],
  )]
  , kind: table
  )

#strong[Skills combine automatically:] - "Create Product catalog" → Domain Model + Pages + Validation

#horizontalrule

== Slide 14: Agentic Search
<slide-14-agentic-search>
=== AI-Powered Code Understanding
<ai-powered-code-understanding>
```sql
/** Query project metadata */
SELECT Name, EntityType, AttributeCount
FROM CATALOG.ENTITIES
WHERE ModuleName = 'Sales';

/** Find duplicate entities */
SELECT e1.Name, e2.Name, COUNT(*) AS MatchingAttrs
FROM CATALOG.ATTRIBUTES a1
JOIN CATALOG.ATTRIBUTES a2 ON a1.Name = a2.Name
WHERE a1.EntityId != a2.EntityId
GROUP BY e1.Name, e2.Name
HAVING COUNT(*) >= 3;
```

#horizontalrule

== Slide 15: Quality Analysis
<slide-15-quality-analysis>
=== Built-in Code Quality Queries
<built-in-code-quality-queries>
- #strong[Duplicate Detection] - Find similar entities across modules
- #strong[Documentation Coverage] - Identify undocumented elements
- #strong[Complexity Analysis] - Find entities needing refactoring
- #strong[Orphan Detection] - Entities with no associations
- #strong[Naming Conventions] - Validate PascalCase compliance
- #strong[Security Audit] - Check access rule coverage

#horizontalrule

== Slide 16: Best Practices as Code
<slide-16-best-practices-as-code>
=== MDL Templates Enforce Standards
<mdl-templates-enforce-standards>
```sql
/**
 * Template: Standard Audit Fields.
 * All entities should include these fields.
 */
@Position(${X}, ${Y})
CREATE PERSISTENT ENTITY ${Module}.${EntityName} (
    ${BusinessFields}

    /** Standard audit fields */
    CreatedAt: DateTime DEFAULT '[%CurrentDateTime%]',
    CreatedBy: String(200),
    ModifiedAt: DateTime,
    ModifiedBy: String(200),
    IsDeleted: Boolean DEFAULT false
);
```

#horizontalrule

== Slide 17: Future Vision
<slide-17-future-vision>
=== Planned Capabilities
<planned-capabilities>
#figure(
  align(center)[#table(
    columns: 2,
    align: (auto,auto,),
    table.header([Feature], [Description],),
    table.hline(),
    [#strong[LSP Support];], [Syntax highlighting, autocomplete, validation],
    [#strong[REST Clients];], [Define external API integrations],
    [#strong[Database Connector];], [Query external databases],
    [#strong[OData Publishing];], [Expose entities as OData services],
    [#strong[Workflow Definition];], [Business process automation],
  )]
  , kind: table
  )

#horizontalrule

== Slide 18: LSP Benefits
<slide-18-lsp-benefits>
=== Language Server Protocol
<language-server-protocol>
#strong[For Developers:] - Syntax highlighting - Context-aware autocomplete - Real-time validation - Go to Definition / Find References

#strong[For AI Tools:] - Structured semantic context - Validation feedback on generated code - Rich symbol information

#horizontalrule

== Slide 19: Summary
<slide-19-summary>
=== mxcli Transforms Mendix Development
<mxcli-transforms-mendix-development>
#figure(
  align(center)[#table(
    columns: 2,
    align: (auto,auto,),
    table.header([Capability], [Benefit],),
    table.hline(),
    [#strong[MDL Language];], [Human and AI-readable definitions],
    [#strong[GenAI Integration];], [Natural language to features],
    [#strong[Token Efficiency];], [5-10x cheaper, more context],
    [#strong[Template System];], [Enforce organizational standards],
    [#strong[Agentic Search];], [AI-powered project understanding],
  )]
  , kind: table
  )

#horizontalrule

== Slide 20: Getting Started
<slide-20-getting-started>
=== Quick Start
<quick-start>
```bash
# Navigate to your Mendix project
cd /path/to/your-mendix-project

# Initialize mxcli
./mxcli init

# Start the REPL
./mxcli

# Connect and explore
mendix> CONNECT LOCAL 'MyProject.mpr';
mendix> SHOW MODULES;
mendix> DESCRIBE ENTITY Sales.Customer;
```

#horizontalrule

== Slide 21: Call to Action
<slide-21-call-to-action>
=== Next Steps
<next-steps>
+ #strong[Try mxcli] in a development project
+ #strong[Explore MDL syntax] with existing models
+ #strong[Integrate with Claude Code] for AI-assisted development
+ #strong[Define templates] for your organization's standards
+ #strong[Provide feedback] to shape future development

#horizontalrule

== Slide 22: Questions?
<slide-22-questions>
= Thank You
<thank-you>
#strong[Resources:] - Documentation: `docs/` - MDL Syntax Reference: `docs/02-features/mdl/` - Example Projects: `templates/`

#horizontalrule
